name: dart_anticaptcha
description: Easy to use library for solving captcha
version: 1.1.4
homepage: http://universium.xyz/

environment:
  sdk: '>=2.15.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  http: ^0.13.4

